---
- name: Update list of available packages
  apt:
    update_cache: yes
    force_apt_get: yes
    upgrade: "dist"

- name: Install wget and unzip
  apt:
    name: ['wget', 'unzip']
    state: present
