---
- name: Add apt key for nodesource
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add repo for nodesource
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main'
    update_cache: yes

- name: Install Nodejs
  apt:
    name: nodejs
    state: present
