---
- name: Run Certbot
  pause:
    prompt: Update DNS to point to {{ server_ip }} and type yes. If you don't want to run certbot, type no.
  register: run_certbot

- name: Install Certbot
  apt:
    name: [ "certbot", "python3-certbot-nginx" ]
    state: present
    update_cache: True
  when: run_certbot

- name: Get Let's Encrypt Certificate
  command: "certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos -m {{ admin_email }}"
  when: run_certbot
